### ISSUE TITLE
Bigode does not answer properly when he is called only by his name

### ISSUE THREAD

**Issue by isadoramariamendes** [calamar-io/calamarcopollo#12] opened 2016-06-30 12:59 UTC
**Current behavior:**
Bigode does not answer properly when he is called only by his name as in the following example:

![img_0233](https://cloud.githubusercontent.com/assets/9004719/16488910/4bed444e-3ea9-11e6-9266-2f664a8faf97.PNG)

**Expected behavior:**
To greet the user and offer some help.

**Comment by GabrielSoga** [comment] 2016-06-30 13:07
dupe of #6

**Closed** 2016-06-30 13:13 UTC
Labels: bigode, duplicate, personality
